#!/usr/bin/env Rscript
library(knitr)
#knit('Eigenanatomy1.Rnw',tangle=TRUE)

knit('Eigenanatomy1.Rnw',tangle=FALSE)
for ( i in c(1,2,3) ) {
  system('pdflatex Eigenanatomy1 ')
  system('bibtex Eigenanatomy1 ')
}
system('rm *log *aux *blg ')

